### ISSUE TITLE
Crash with Fabric API 0.3.0

### ISSUE THREAD

**Issue by Madis0** [polgaria/consolehud#1]
The latest ConsoleHUD does not work with the latest Fabric API on stable 1.14.1.

- Minecraft 1.14.1
- Fabric Loader 0.4.7 b 147
- Fabric API 0.3.0 pre-build 157 (which is the latest for 1.14.1; also tested with build 161 which is meant for 1.14.2 pre-release 2)
- Console HUD 1.1.1 b 4

<details>
 <summary>Launcher crash log</summary>

```
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 18.05.19 10:56
Description: Initializing game

java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:101)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:93)
	at net.fabricmc.loader.EntrypointStorage.getEntrypoints(EntrypointStorage.java:140)
	at net.fabricmc.loader.FabricLoader.getEntrypoints(FabricLoader.java:186)
	at net.fabricmc.loader.entrypoint.hooks.EntrypointClient.start(EntrypointClient.java:35)
	at net.minecraft.class_310.method_1503(class_310.java)
	at net.minecraft.class_310.method_1514(class_310.java:395)
	at net.minecraft.client.main.Main.main(Main.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: java.lang.TypeNotPresentException: Type net/minecraft/class_1657 not present
	at org.spongepowered.asm.lib.ClassWriter.getCommonSuperClass(ClassWriter.java:931)
	at org.spongepowered.asm.lib.SymbolTable.addMergedType(SymbolTable.java:1200)
	at org.spongepowered.asm.lib.Frame.merge(Frame.java:1299)
	at org.spongepowered.asm.lib.Frame.merge(Frame.java:1244)
	at org.spongepowered.asm.lib.MethodWriter.computeAllFrames(MethodWriter.java:1607)
	at org.spongepowered.asm.lib.MethodWriter.visitMaxs(MethodWriter.java:1543)
	at org.spongepowered.asm.lib.MethodVisitor.visitMaxs(MethodVisitor.java:762)
	at org.spongepowered.asm.mixin.injection.invoke.arg.ArgsClassGenerator.generateIndexedSetter(ArgsClassGenerator.java:390)
	at org.spongepowered.asm.mixin.injection.invoke.arg.ArgsClassGenerator.gener<details>
 <summary>Launcher crash log</summary>ateSetters(ArgsClassGenerator.java:326)
	at org.spongepowered.asm.mixin.injection.invoke.arg.ArgsClassGenerator.generateClass(ArgsClassGenerator.java:189)
	at org.spongepowered.asm.mixin.injection.invoke.arg.ArgsClassGenerator.getBytes(ArgsClassGenerator.java:160)
	at org.spongepowered.asm.mixin.injection.invoke.arg.ArgsClassGenerator.generate(ArgsClassGenerator.java:143)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:435)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:169)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:142)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.fuzs.consolehud.ConsoleHud.<clinit>(ConsoleHud.java:16)
	... 18 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_1657
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.spongepowered.asm.lib.ClassWriter.getCommonSuperClass(ClassWriter.java:929)
	... 34 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:101)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:93)
	at net.fabricmc.loader.EntrypointStorage.getEntrypoints(EntrypointStorage.java:140)
	at net.fabricmc.loader.FabricLoader.getEntrypoints(FabricLoader.java:186)
	at net.fabricmc.loader.entrypoint.hooks.EntrypointClient.start(EntrypointClient.java:35)
	at net.minecraft.class_310.method_1503(class_310.java)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.class_310.method_1514(class_310.java:395)
	at net.minecraft.client.main.Main.main(Main.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.14.1
	Operating System: Linux (amd64) version 4.19.36-1-MANJARO
	Java Version: 1.8.0_212, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 643036776 bytes (613 MB) / 872415232 bytes (832 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		autoconfig1: Auto Config v1 1.1.0+mc1.14.1
		cloth-config: Cloth Config 0.2.1+build.14
		consolehud: ConsoleHUD 1.1.1+build.4
		fabric: Fabric API 0.3.0-pre+build.157
		fabric-api-base: fabric-api-base 0.1.0+f1618918
		fabric-commands-v0: fabric-commands-v0 0.1.0+f1618918
		fabric-containers-v0: fabric-containers-v0 0.1.0+f1618918
		fabric-content-registries-v0: fabric-content-registries-v0 0.1.0+f1618918
		fabric-crash-report-info-v1: fabric-crash-report-info-v1 0.1.0+f1618918
		fabric-events-interaction-v0: fabric-events-interaction-v0 0.1.0+f1618918
		fabric-events-lifecycle-v0: fabric-events-lifecycle-v0 0.1.0+9232ac87
		fabric-item-groups-v0: fabric-item-groups-v0 0.1.0+f1618918
		fabric-keybindings-v0: fabric-keybindings-v0 0.1.0+f1618918
		fabric-mining-levels-v0: fabric-mining-levels-v0 0.1.0+f1618918
		fabric-models-v0: fabric-models-v0 0.1.0+f1618918
		fabric-networking-blockentity-v0: fabric-networking-blockentity-v0 0.1.0+f1618918
		fabric-networking-v0: fabric-networking-v0 0.1.1+57f0d19c
		fabric-object-builders-v0: fabric-object-builders-v0 0.1.0+9232ac87
		fabric-registry-sync-v0: fabric-registry-sync-v0 0.1.0+f1618918
		fabric-rendering-v0: fabric-rendering-v0 0.1.0+f1618918
		fabric-resource-loader-v0: fabric-resource-loader-v0 0.1.0+f1618918
		fabric-tag-extensions-v0: fabric-tag-extensions-v0 0.1.0+f1618918
		fabric-textures-v0: fabric-textures-v0 0.1.0+f1618918
		fabricloader: Fabric Loader 0.4.7+build.147
	Launched Version: fabric-loader-0.4.7+build.147-1.14.1+build.4
	LWJGL: 3.2.1 build 12
	OpenGL: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: ~~ERROR~~ NullPointerException: null
	Current Language: ~~ERROR~~ NullPointerException: null
	CPU: <unknown>

```
</details>

**Comment by geniiii** [comment]
can reproduce, but have no idea why it happens 🤷‍♀️

**Comment by Madis0** [comment]
Works on v1.0.2, but seeing the number I'm not sure whether you consider it a "fix".

**Comment by geniiii** [comment]
not a fix, it's a 1.1-specific issue (Mixin workaround failing)  
i'll think of a better way to do the whole hovering hotbar thing, eventually

**Comment by Madis0** [comment]
In v1.0.3+build.6 it does not crash, but for some reason it initially displays all three - name, enchantment and lore and after a short while, only displays the name and enchantment. 
The tooltip in the inventory doesn't display the lore at all.
