### ISSUE TITLE
Incorrect item's Lore preview

### ISSUE THREAD

**Issue by fixator10** [polgaria/consolehud#2]
Items with formatted lore shows in ConsoleHUD incorrectly
![item](https://Moeka.is-a-good-waifu.com/3Bpj8RH.png)
![preview](https://Moeka.is-a-good-waifu.com/9XhYuwQ.png)
NBT data parsed via custom 1.13 client:
```json
"nbt": {
	"": {
		"display": {
			"Lore": [
				"§7Mystery Dust: §b???",
				"§7Hypixel Credits: §b50",
				"",
				"§7Collect fun cosmetic items!",
				"§7Get new items by opening",
				"§bMystery Boxes §7or hitting milestone rewards.",
				"§7Some can also be crafted using",
				"§bMystery Dust§7.",
				"",
				"§bMystery Dust §7can be earned by",
				"§7opening §bMystery Boxes.",
				"",
				"§7You can support the Hypixel server by",
				"§7buying §bMystery Boxes §7on our store:",
				"",
				"§ehttp://store.hypixel.net"
			],
			"Name": "{\"extra\":[{\"italic\":false,\"extra\":[{\"color\":\"green\",\"text\":\"Collectibles \"},{\"color\":\"gray\",\"text\":\"(Right Click)\"}],\"text\":\"\"}],\"text\":\"\"}"
		},
		"AttributeModifiers": []
	}
}

```

Mod version: ConsoleHUD-1.0.1+build.2 (latest stable release)

**Comment by geniiii** [comment]
should be fixed as of commit 305d8e2ffad55ec440a79b00a6d08f4fc6144cdb  
![fixed](https://f.geni.site/gt.png)

**Comment by Madis0** [comment]
FWIW, got a crash on a custom item (stone with speed attribute and colored name) on v1.0.2.

```
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
	at com.google.gson.internal.Streams.parse(Streams.java:60)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:65)
	at net.minecraft.class_3518.method_15267(class_3518.java:493)
	at net.minecraft.class_3518.method_15279(class_3518.java:518)
	at net.minecraft.class_2561$class_2562.method_10877(class_2561.java:393)
	at com.fuzs.consolehud.renders.RenderSelectedItem.getTooltip(RenderSelectedItem.java:216)
	at com.fuzs.consolehud.renders.RenderSelectedItem.setTooltipColor(RenderSelectedItem.java:136)
	at com.fuzs.consolehud.renders.RenderSelectedItem.onInGameHudDraw(RenderSelectedItem.java:94)
	at com.fuzs.consolehud.renders.RenderSelectedItem.access$100(RenderSelectedItem.java:32)
	at com.fuzs.consolehud.renders.RenderSelectedItem$EventHandler.lambda$registerInGameHudDrawEvent$0(RenderSelectedItem.java:236)
	at site.geni.renderevents.callbacks.client.InGameHudDrawCallback$Pre.lambda$null$0(InGameHudDrawCallback.java:14)
	at net.minecraft.class_329.handler$drawPre$zfo000(class_329.java:3302)
	at net.minecraft.class_329.method_1753(class_329.java)
	at net.minecraft.class_757.method_3192(class_757.java:657)
	at net.minecraft.class_310.method_1523(class_310.java:954)
	at net.minecraft.class_310.method_1514(class_310.java:411)
	at net.minecraft.client.main.Main.main(Main.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1401)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:593)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
	at com.google.gson.internal.Streams.parse(Streams.java:46)
	... 23 more
```

**Comment by geniiii** [comment]
> 
> 
> FWIW, got a crash on a custom item (stone with speed attribute and colored name) on v1.0.2.
> 
> ```
> com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
> 	at com.google.gson.internal.Streams.parse(Streams.java:60)
> 	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:65)
> 	at net.minecraft.class_3518.method_15267(class_3518.java:493)
> 	at net.minecraft.class_3518.method_15279(class_3518.java:518)
> 	at net.minecraft.class_2561$class_2562.method_10877(class_2561.java:393)
> 	at com.fuzs.consolehud.renders.RenderSelectedItem.getTooltip(RenderSelectedItem.java:216)
> 	at com.fuzs.consolehud.renders.RenderSelectedItem.setTooltipColor(RenderSelectedItem.java:136)
> 	at com.fuzs.consolehud.renders.RenderSelectedItem.onInGameHudDraw(RenderSelectedItem.java:94)
> 	at com.fuzs.consolehud.renders.RenderSelectedItem.access$100(RenderSelectedItem.java:32)
> 	at com.fuzs.consolehud.renders.RenderSelectedItem$EventHandler.lambda$registerInGameHudDrawEvent$0(RenderSelectedItem.java:236)
> 	at site.geni.renderevents.callbacks.client.InGameHudDrawCallback$Pre.lambda$null$0(InGameHudDrawCallback.java:14)
> 	at net.minecraft.class_329.handler$drawPre$zfo000(class_329.java:3302)
> 	at net.minecraft.class_329.method_1753(class_329.java)
> 	at net.minecraft.class_757.method_3192(class_757.java:657)
> 	at net.minecraft.class_310.method_1523(class_310.java:954)
> 	at net.minecraft.class_310.method_1514(class_310.java:411)
> 	at net.minecraft.client.main.Main.main(Main.java:154)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
> 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127)
> 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
> Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
> 	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
> 	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1401)
> 	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:593)
> 	at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
> 	at com.google.gson.internal.Streams.parse(Streams.java:46)
> 	... 23 more
> ```

open a new issue, i'll look into this
