### ISSUE TITLE
Custom item crash

### ISSUE THREAD

**Issue by Madis0** [polgaria/consolehud#4]
Got a crash on a custom item (stone with speed attribute and colored name) on v1.0.2.

```
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
	at com.google.gson.internal.Streams.parse(Streams.java:60)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:65)
	at net.minecraft.class_3518.method_15267(class_3518.java:493)
	at net.minecraft.class_3518.method_15279(class_3518.java:518)
	at net.minecraft.class_2561$class_2562.method_10877(class_2561.java:393)
	at com.fuzs.consolehud.renders.RenderSelectedItem.getTooltip(RenderSelectedItem.java:216)
	at com.fuzs.consolehud.renders.RenderSelectedItem.setTooltipColor(RenderSelectedItem.java:136)
	at com.fuzs.consolehud.renders.RenderSelectedItem.onInGameHudDraw(RenderSelectedItem.java:94)
	at com.fuzs.consolehud.renders.RenderSelectedItem.access$100(RenderSelectedItem.java:32)
	at com.fuzs.consolehud.renders.RenderSelectedItem$EventHandler.lambda$registerInGameHudDrawEvent$0(RenderSelectedItem.java:236)
	at site.geni.renderevents.callbacks.client.InGameHudDrawCallback$Pre.lambda$null$0(InGameHudDrawCallback.java:14)
	at net.minecraft.class_329.handler$drawPre$zfo000(class_329.java:3302)
	at net.minecraft.class_329.method_1753(class_329.java)
	at net.minecraft.class_757.method_3192(class_757.java:657)
	at net.minecraft.class_310.method_1523(class_310.java:954)
	at net.minecraft.class_310.method_1514(class_310.java:411)
	at net.minecraft.client.main.Main.main(Main.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1401)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:593)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
	at com.google.gson.internal.Streams.parse(Streams.java:46)
	... 23 more
```

**Comment by geniiii** [comment]
can't quite replicate it, got a save with this item?

**Comment by Madis0** [comment]
It should be similar to
```/give @p minecraft:stone{display:{Name:"{\"text\":\"Colored name\",\"color\":\"blue\"}",Lore:["{\"text\":\"Test lore\"}"]},HideFlags:2,AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"generic.movementSpeed",Amount:5,Operation:0,UUIDLeast:28229,UUIDMost:234670}]} 1```,
however it is a player-restricted item on a server so I don't know the exact command (and could not reproduce it with this one either).

**Comment by Madis0** [comment]
Got the real command now:
```
/give @p stone{AttributeModifiers:[{Operation:0,UUIDLeast:1,UUIDMost:1,Amount:0.3,AttributeName:generic.movementSpeed,Name:Turbo}],display:{Name:"{\"text\":\"Turbo\",\"italic\":false}",Lore:["Gotta go fast"]},Enchantments:[{id:"minecraft:protection",lvl:1}],HideFlags:31} 1
```

**Comment by geniiii** [comment]
should hopefully be "fixed" by 007d0c78ec81a4c8cc3b83c0160692b8e6e7c646, although i won't release a build just yet

**Comment by Madis0** [comment]
In v1.0.3+build.6 it does not crash, but for some reason it initially displays all three - name, enchantment and lore and after a short while, only displays the name and enchantment. 
The tooltip in the inventory doesn't display the lore at all.

**Comment by Madis0** [comment]
The issue I previously mentioned seems to be partly fixed - it only appears on singleplayer now (while previously it was seen on the server too).
